### ISSUE TITLE
PDF version not available

### ISSUE THREAD

**Issue by andland** [ermeel86/surv_stan_stancon2019#1]
The [compiled PDF version](https://github.com/ermeel86/stan_surv_stancon2019/survmodelsrstanarm.pdf) linked in the README is not there.

**Comment by ermeel86** [comment]
Thank you! Should be fixed by [this](https://github.com/ermeel86/surv_stan_stancon2019/commit/fb0a142bfef67bff6aabb90dae716818d72bf891) commit.
